# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do

    lane :generateClipReport do |options|
        scheme = options[:scheme]
        config = options[:config]
        build_number = options[:build_number]
        report_path = options[:report_path]

        UI.message "Start"
        build_clip(scheme: "RobertHalf", configuration: "Adhoc", export_method: "ad-hoc", report_output_path: "Report.txt", clip_bundle_id: "com.x.y")
        app_clip_size_report(report_path: report_path)

    end
end
