# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do

    lane :generateClipReport do |options|
        report_output_path = options[:report_output_path]
        UI.message("Report output path: #{report_output_path}")

        build_clip(scheme: options[:scheme],
          configuration: options[:configuration],
          export_method: options[:export_method],
          report_output_path: report_output_path,
          clip_bundle_id: options[:clip_bundle_id])

        app_clip_size_report(report_path: report_output_path,
                             include_on_demand_resources: options[:include_on_demand_resources],
                             include_variant_descriptors: options[:include_variant_descriptors])
    end
end
